[package]
name = "stupid-os"
version = "0.1.0"
edition = "2021"
authors = ["Phusit Somboonyingsuk"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
log = "0.4.19"
uefi = "0.24.0"
uefi-services = "0.21.0"

